import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const frontendRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

process.env.TSX_TSCONFIG_PATH = 'tsconfig.app.json';

const result = spawnSync(
  process.execPath,
  [
    '--import',
    'tsx',
    '--test',
    'src/components/chronology/worldAdvanceFeedGrouping.test.ts',
    'src/lib/chronologyDates.test.ts',
    'src/lib/wikiHierarchy.test.ts',
    'src/lib/wikiIndexEntry.test.ts',
    'src/lib/wikiAutoLink.test.ts',
    'src/lib/campaignPaths.test.ts',
    'src/lib/sessionSnapshotFormat.test.ts',
    'src/hooks/useIdentityDisplay.test.ts',
    'src/utils/sessionNoteConstants.test.ts',
    'src/lib/configSchemaParser.test.ts',
    'src/lib/questHubLayout.test.ts',
    'src/lib/questHubFilters.test.ts',
    'src/lib/questLifecycleDisplay.test.ts',
    'src/lib/threadHubFilters.test.ts',
    'src/lib/questBoardOrder.test.ts',
    'src/lib/projectionProvenance.test.ts',
    'src/lib/entityProjectionDebug.test.ts',
    'src/lib/stanceVisuals.test.ts',
    'src/lib/temporalStatusBadge.test.ts',
    'src/lib/entityProjectionQueries.test.ts',
    'src/lib/organizationMetadata.test.ts',
    'src/lib/characterMetadata.test.ts',
    'src/lib/createEntityConfig.test.ts',
    'src/lib/entityAppearanceProjection.test.ts',
    'src/lib/characterIdentityProjection.test.ts',
    'src/lib/bestiaryIdentityProjection.test.ts',
    'src/lib/bestiaryBrowseProjection.test.ts',
    'src/lib/bestiaryHubGrouping.test.ts',
    'src/lib/organizationIdentityProjection.test.ts',
    'src/lib/familyIdentityProjection.test.ts',
    'src/lib/entitySurfaceProfile.test.ts',
    'src/lib/pass2EntitySurfaces.test.ts',
    'src/lib/buildPartyProjection.test.ts',
    'src/lib/characterConnectionProjection.test.ts',
    'src/lib/categoryIndexBrowse.test.ts',
    'src/lib/campaignHeaderSubtitle.test.ts',
    'src/hooks/useCampaignSearch.test.ts',
    'src/lib/characterHubGrouping.test.ts',
    'src/lib/characterHubRailWidthPreference.test.ts',
    'src/lib/codexHierarchy.test.ts',
    'src/lib/codexMeasure.test.ts',
    'src/lib/contentPriorityCollapse.test.ts',
    'src/lib/entityWorkspaceSlots.test.ts',
    'src/lib/entityIdentityStripAdapter.test.ts',
    'src/lib/entityWorkspaceEmphasis.test.ts',
    'src/lib/workspaceComposition.test.ts',
    'src/components/IndexGridView.characters.test.ts',
    'src/lib/hierarchyExpansionState.test.ts',
    'src/lib/entityBrowserProjection.test.ts',
    'src/utils/wikiLayoutRuntime.test.ts',
    'src/lib/blockCapabilities.test.ts',
    'src/lib/blockSemanticIndex.test.ts',
    'src/components/wiki/extensions/wikiReferenceInsertion.test.ts',
    'src/components/wiki/extensions/wikiLinkKeyboard.test.ts',
    'src/components/wiki/extensions/slashSuggestionPlugin.test.ts',
    'src/components/wiki/extensions/EditorHighlightExtension.test.ts',
    'src/components/wiki/extensions/EditorTextColorExtension.test.ts',
    'src/lib/editor/editorColorTokens.test.ts',
    'src/hooks/useBlockDraft.test.ts',
    'src/lib/loreSemanticBundle.test.ts',
    'src/lib/wikiPageSubviews.test.ts',
    'src/lib/theme/atmosphericDerivation.test.ts',
    'src/lib/theme/sceneComposition.test.ts',
    'src/lib/theme/sidebarNavDerivation.test.ts',
    'src/lib/theme/luminanceEcology.test.ts',
    'src/lib/theme/themeStack.test.ts',
    'src/lib/hubAmbientTheme.test.ts',
  ],
  { cwd: frontendRoot, stdio: 'inherit', env: process.env },
);

process.exit(result.status ?? 1);
