import { randomUUID } from 'node:crypto';
import type { Response } from 'express';
import type { CampaignScopedRequest } from '../middleware/campaignScope.js';
import { encryptSecretOrDevStore } from '../lib/crypto/secretBox.js';
import { deliverDiscord } from '../lib/discord/delivery.js';
import { discordEventCatalog, discordTestPayload, validatesDiscordSubscriptions } from '../lib/discord/formatter.js';
import { prisma } from '../lib/prisma.js';
import { assertUrlSafeForImport } from '../lib/ssrfGuard.js';

const dto=(row:any)=>({id:row.id,name:row.name,enabled:row.enabled,subscribedEvents:row.subscribedEvents,announcementOptions:row.announcementOptions,suspendedAt:row.suspendedAt,consecutiveFailures:row.consecutiveFailures,lastSucceededAt:row.lastSucceededAt,lastFailedAt:row.lastFailedAt,lastError:row.lastError,connected:true,createdAt:row.createdAt,updatedAt:row.updatedAt});
async function discordUrl(value:unknown):Promise<string>{if(typeof value!=='string')throw new Error('Discord webhook URL is required');const url=new URL(value);if(url.protocol!=='https:'||!['discord.com','discordapp.com'].includes(url.hostname)||!/^\/api\/webhooks\/\d+\/[A-Za-z0-9._-]+\/?$/.test(url.pathname))throw new Error('Enter a valid HTTPS Discord webhook URL');url.search='';url.hash='';await assertUrlSafeForImport(url,{allowHttp:false});return url.toString();}
export function getDiscordCatalog(_req:CampaignScopedRequest,res:Response):void{res.json({events:discordEventCatalog});}
export async function listDiscord(req:CampaignScopedRequest,res:Response):Promise<void>{const destinations=await prisma.discordDestination.findMany({where:{campaignId:req.campaign!.campaignId},orderBy:{createdAt:'desc'}});res.json({destinations:destinations.map(dto)});}
export async function createDiscord(req:CampaignScopedRequest,res:Response):Promise<void>{try{const name=typeof req.body.name==='string'?req.body.name.trim().slice(0,120):'';if(!name||!validatesDiscordSubscriptions(req.body.subscribedEvents))return void res.status(400).json({error:'Name and supported announcement events are required'});const url=await discordUrl(req.body.webhookUrl);const row=await prisma.discordDestination.create({data:{campaignId:req.campaign!.campaignId,name,webhookUrlEnc:encryptSecretOrDevStore(url),enabled:req.body.enabled!==false,subscribedEvents:req.body.subscribedEvents,announcementOptions:req.body.announcementOptions??{},createdById:req.user!.id}});res.status(201).json({destination:dto(row)});}catch(error){res.status(400).json({error:error instanceof Error?error.message:'Invalid Discord destination'});}}
export async function updateDiscord(req:CampaignScopedRequest,res:Response):Promise<void>{const row=await prisma.discordDestination.findFirst({where:{id:String(req.params.destinationId),campaignId:req.campaign!.campaignId}});if(!row)return void res.status(404).json({error:'Discord destination not found'});try{const data:any={};if(req.body.name!==undefined)data.name=String(req.body.name).trim().slice(0,120);if(req.body.webhookUrl!==undefined)data.webhookUrlEnc=encryptSecretOrDevStore(await discordUrl(req.body.webhookUrl));if(req.body.subscribedEvents!==undefined){if(!validatesDiscordSubscriptions(req.body.subscribedEvents))throw new Error('Unsupported Discord announcement event');data.subscribedEvents=req.body.subscribedEvents;}if(req.body.enabled!==undefined){data.enabled=Boolean(req.body.enabled);if(data.enabled){data.suspendedAt=null;data.consecutiveFailures=0;}}const updated=await prisma.discordDestination.update({where:{id:row.id},data});res.json({destination:dto(updated)});}catch(error){res.status(400).json({error:error instanceof Error?error.message:'Invalid Discord destination'});}}
export async function deleteDiscord(req:CampaignScopedRequest,res:Response):Promise<void>{const result=await prisma.discordDestination.deleteMany({where:{id:String(req.params.destinationId),campaignId:req.campaign!.campaignId}});res.status(result.count?204:404).end();}
export async function testDiscord(req:CampaignScopedRequest,res:Response):Promise<void>{const destination=await prisma.discordDestination.findFirst({where:{id:String(req.params.destinationId),campaignId:req.campaign!.campaignId},include:{campaign:{select:{name:true}}}});if(!destination)return void res.status(404).json({error:'Discord destination not found'});const id=`evt_${randomUUID()}`;const delivery=await prisma.discordDelivery.create({data:{campaignId:destination.campaignId,destinationId:destination.id,eventId:id,eventType:'discord.test',payload:discordTestPayload(destination.campaign.name),isTest:true}});setImmediate(()=>void deliverDiscord(delivery.id));res.status(202).json({deliveryId:delivery.id});}
export async function listDiscordDeliveries(req:CampaignScopedRequest,res:Response):Promise<void>{const rows=await prisma.discordDelivery.findMany({where:{campaignId:req.campaign!.campaignId,destinationId:String(req.params.destinationId)},select:{id:true,eventType:true,status:true,attemptCount:true,responseStatus:true,diagnostic:true,isTest:true,deliveredAt:true,createdAt:true},orderBy:{createdAt:'desc'},take:100});res.json({deliveries:rows});}
