import { useEffect, useState } from 'react';
import { createWebhook, deleteWebhook, fetchWebhookCatalog, fetchWebhookDeliveries, fetchWebhooks, patchWebhook, redeliverWebhook, rotateWebhook, testWebhook, type WebhookCatalogEvent, type WebhookDelivery, type WebhookEndpoint } from '@/lib/webhooks';

export function CampaignWebhooksSettings({ campaignHandle }: { campaignHandle:string }) {
  const [endpoints,setEndpoints]=useState<WebhookEndpoint[]>([]); const [catalog,setCatalog]=useState<WebhookCatalogEvent[]>([]);
  const [name,setName]=useState(''); const [url,setUrl]=useState(''); const [selected,setSelected]=useState<string[]>([]); const [notice,setNotice]=useState('');
  const [deliveries,setDeliveries]=useState<Record<string,WebhookDelivery[]>>({});
  const load=()=>Promise.all([fetchWebhooks(campaignHandle),fetchWebhookCatalog(campaignHandle)]).then(([a,b])=>{setEndpoints(a.endpoints);setCatalog(b.events);});
  useEffect(()=>{void load();},[campaignHandle]);
  return <div className="rounded-lg border border-border bg-surface p-6 space-y-5">
    <div><h2 className="text-lg font-semibold text-white">Outgoing webhooks</h2><p className="text-sm text-muted">Send selected public campaign events to an HTTPS endpoint. Session presence, cursors, and typing are never included.</p></div>
    {notice&&<p className="rounded border border-border bg-elevated p-3 text-sm text-foreground">{notice}</p>}
    <form className="space-y-3" onSubmit={e=>{e.preventDefault();void createWebhook(campaignHandle,{name,url,subscribedEvents:selected}).then(r=>{setNotice(`Webhook created. Copy this secret now: ${r.secret}`);setName('');setUrl('');setSelected([]);return load();}).catch(e=>setNotice(e instanceof Error?e.message:'Unable to create webhook'));}}>
      <div className="grid gap-3 sm:grid-cols-2"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Endpoint name" className="rounded border border-border bg-elevated px-3 py-2"/><input required type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com/webhook" className="rounded border border-border bg-elevated px-3 py-2"/></div>
      <div className="grid gap-2 sm:grid-cols-2">{catalog.map(item=><label key={item.type} className="text-sm text-foreground"><input type="checkbox" checked={selected.includes(item.type)} onChange={()=>setSelected(v=>v.includes(item.type)?v.filter(x=>x!==item.type):[...v,item.type])}/> <span className="ml-2">{item.label}</span></label>)}</div>
      <button disabled={!selected.length} className="rounded bg-primary px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Add webhook</button>
    </form>
    <div className="space-y-3">{endpoints.map(endpoint=><div key={endpoint.id} className="rounded border border-border bg-elevated p-4"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-semibold text-foreground">{endpoint.name}</p><p className="break-all text-xs text-muted">{endpoint.url}</p><p className="text-xs text-muted">{endpoint.suspendedAt?'Suspended after repeated failures':endpoint.enabled?'Active':'Inactive'} · {endpoint.consecutiveFailures} consecutive failures</p></div><div className="flex flex-wrap gap-2"><button className="rounded border border-border px-3 py-1 text-sm" onClick={()=>void patchWebhook(campaignHandle,endpoint.id,{enabled:!endpoint.enabled}).then(load)}> {endpoint.enabled?'Disable':'Enable'} </button><button className="rounded border border-border px-3 py-1 text-sm" onClick={()=>void testWebhook(campaignHandle,endpoint.id).then(()=>setNotice('Test delivery queued.'))}>Test</button><button className="rounded border border-border px-3 py-1 text-sm" onClick={()=>void fetchWebhookDeliveries(campaignHandle,endpoint.id).then(r=>setDeliveries(v=>({...v,[endpoint.id]:r.deliveries})))}>History</button><button className="rounded border border-border px-3 py-1 text-sm" onClick={()=>void rotateWebhook(campaignHandle,endpoint.id).then(r=>setNotice(`Secret rotated. Copy it now: ${r.secret}`))}>Rotate secret</button><button className="rounded border border-danger px-3 py-1 text-sm text-danger" onClick={()=>void deleteWebhook(campaignHandle,endpoint.id).then(load)}>Delete</button></div></div>{deliveries[endpoint.id]?.map(d=><div key={d.id} className="mt-2 flex justify-between gap-3 border-t border-border pt-2 text-xs text-muted"><span>{d.eventType} · {d.status} · {d.responseStatus??'no response'}{d.diagnostic?` · ${d.diagnostic}`:''}</span><button onClick={()=>void redeliverWebhook(campaignHandle,d.id).then(()=>setNotice('Redelivery queued.'))}>Redeliver</button></div>)}</div>)}</div>
  </div>;
}
