import { useEffect,useState } from 'react';
import { createDiscord,deleteDiscord,fetchDiscord,fetchDiscordCatalog,fetchDiscordDeliveries,patchDiscord,testDiscord,type DiscordDelivery,type DiscordDestination,type DiscordEvent } from '@/lib/discord';
export function CampaignDiscordSettings({campaignHandle}:{campaignHandle:string}){
 const [destinations,setDestinations]=useState<DiscordDestination[]>([]),[catalog,setCatalog]=useState<DiscordEvent[]>([]),[selected,setSelected]=useState<string[]>([]);const [name,setName]=useState(''),[url,setUrl]=useState(''),[notice,setNotice]=useState('');const [history,setHistory]=useState<Record<string,DiscordDelivery[]>>({});
 const load=()=>Promise.all([fetchDiscord(campaignHandle),fetchDiscordCatalog(campaignHandle)]).then(([a,b])=>{setDestinations(a.destinations);setCatalog(b.events);});useEffect(()=>{void load();},[campaignHandle]);
 return <section className="space-y-5 rounded-lg border border-border bg-surface p-6"><div><h2 className="text-lg font-semibold text-white">Discord announcements</h2><p className="text-sm text-muted">Send readable campaign announcements to one or more Discord channels.</p></div>{notice&&<p className="rounded border border-border bg-elevated p-3 text-sm text-foreground">{notice}</p>}
 <form className="space-y-3" onSubmit={e=>{e.preventDefault();void createDiscord(campaignHandle,{name,webhookUrl:url,subscribedEvents:selected}).then(()=>{setName('');setUrl('');setSelected([]);setNotice('Discord destination connected.');return load();}).catch(e=>setNotice(e instanceof Error?e.message:'Unable to connect Discord'));}}><div className="grid gap-3 sm:grid-cols-2"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Destination name" className="rounded border border-border bg-elevated px-3 py-2"/><input required type="password" autoComplete="new-password" value={url} onChange={e=>setUrl(e.target.value)} placeholder="Discord webhook URL" className="rounded border border-border bg-elevated px-3 py-2"/></div><div className="grid gap-2 sm:grid-cols-2">{catalog.map(item=><label key={item.type} className="text-sm text-foreground"><input type="checkbox" checked={selected.includes(item.type)} onChange={()=>setSelected(v=>v.includes(item.type)?v.filter(x=>x!==item.type):[...v,item.type])}/><span className="ml-2">{item.label}</span></label>)}</div><button disabled={!selected.length} className="rounded bg-primary px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Connect Discord</button></form>
 <div className="space-y-3">{destinations.map(d=><div key={d.id} className="rounded border border-border bg-elevated p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold text-foreground">{d.name}</p><p className="text-xs text-muted">{d.suspendedAt?'Suspended':d.enabled?'Healthy / active':'Inactive'} · Last success: {d.lastSucceededAt?new Date(d.lastSucceededAt).toLocaleString():'never'} · Last failure: {d.lastFailedAt?new Date(d.lastFailedAt).toLocaleString():'never'}</p>{d.lastError&&<p className="text-xs text-danger">{d.lastError}</p>}</div><div className="flex flex-wrap gap-2"><button onClick={()=>void patchDiscord(campaignHandle,d.id,{enabled:!d.enabled}).then(load)}>{d.enabled?'Disable':'Enable'}</button><button onClick={()=>{const replacement=window.prompt('Paste the replacement Discord webhook URL');if(replacement)void patchDiscord(campaignHandle,d.id,{webhookUrl:replacement}).then(()=>setNotice('Discord webhook replaced.'));}}>Replace URL</button><button onClick={()=>void testDiscord(campaignHandle,d.id).then(()=>setNotice('Discord test queued.'))}>Test</button><button onClick={()=>void fetchDiscordDeliveries(campaignHandle,d.id).then(r=>setHistory(v=>({...v,[d.id]:r.deliveries})))}>History</button><button className="text-danger" onClick={()=>void deleteDiscord(campaignHandle,d.id).then(load)}>Disconnect</button></div></div>{history[d.id]?.map(row=><p key={row.id} className="mt-2 border-t border-border pt-2 text-xs text-muted">{row.isTest?'Test':row.eventType} · {row.status} · {row.responseStatus??'no response'}{row.diagnostic?` · ${row.diagnostic}`:''}</p>)}</div>)}</div></section>;
}
