/**
 * Phase 6 — world event consequences (GM-authored, manually applied).
 * Stored on event-lore wiki metadata (`event-{calendarEventId}`).
 */
export declare const EVENT_HAVEN_THREAT_SEVERITIES: readonly ["low", "rising", "critical"];
export type EventHavenThreatSeverity = (typeof EVENT_HAVEN_THREAT_SEVERITIES)[number];
export declare const EVENT_CONSEQUENCE_VERSION = "event-consequence-v1";
export declare const EVENT_CONSEQUENCE_METADATA_KEY = "eventConsequences";
export declare const EVENT_LORE_AUTO_GENERATED_METADATA_KEY = "eventLoreAutoGenerated";
export declare const EVENT_CONSEQUENCE_KINDS: readonly ["quest_hook", "alter_location", "route_change", "haven_threat"];
export type EventConsequenceKind = (typeof EVENT_CONSEQUENCE_KINDS)[number];
export declare const EVENT_CONSEQUENCE_APPLICATION_STATES: readonly ["pending", "complete", "partial", "blocked"];
export type EventConsequenceApplicationState = (typeof EVENT_CONSEQUENCE_APPLICATION_STATES)[number];
export declare const EVENT_CONSEQUENCE_APPLICATION_SOURCES: readonly ["manual_apply", "preview"];
export type EventConsequenceApplicationSource = (typeof EVENT_CONSEQUENCE_APPLICATION_SOURCES)[number];
export declare const QUEST_HOOK_MODES: readonly ["discover_quest", "open_thread"];
export type QuestHookMode = (typeof QUEST_HOOK_MODES)[number];
export declare const ROUTE_CHANGE_SEVERITIES: readonly ["minor", "major"];
export type RouteChangeSeverity = (typeof ROUTE_CHANGE_SEVERITIES)[number];
export declare const ROUTE_CHANGE_REASONS: readonly ["war", "banditry", "disaster", "other"];
export type RouteChangeReason = (typeof ROUTE_CHANGE_REASONS)[number];
export type EventConsequenceTargets = {
    pageIds?: string[];
    havenIds?: string[];
    locationIds?: string[];
};
export type QuestHookPayload = {
    mode: QuestHookMode;
};
export type AlterLocationPayload = Record<string, never>;
export type RouteChangePayload = {
    severity?: RouteChangeSeverity;
    reason?: RouteChangeReason;
};
export type HavenThreatPayload = {
    label: string;
    severity?: EventHavenThreatSeverity | null;
    description?: string | null;
};
export type EventConsequencePayload = QuestHookPayload | AlterLocationPayload | RouteChangePayload | HavenThreatPayload;
export type EventConsequenceApplication = {
    state: EventConsequenceApplicationState;
    appliedAtEpochMinute?: string;
    applicationRunId?: string;
    source?: EventConsequenceApplicationSource;
    warnings?: string[];
    pendingConfirmations?: string[];
};
export type EventConsequence = {
    id: string;
    kind: EventConsequenceKind;
    description?: string;
    targets?: EventConsequenceTargets;
    payload: EventConsequencePayload;
    application?: EventConsequenceApplication;
};
export type EventConsequenceSet = {
    version: typeof EVENT_CONSEQUENCE_VERSION;
    consequences: EventConsequence[];
};
export type EventConsequencePreviewRow = {
    consequenceId: string;
    kind: EventConsequenceKind;
    projectedState: 'complete' | 'partial' | 'blocked';
    summary: string;
    warnings: string[];
    pendingConfirmations: string[];
};
export type EventConsequenceApplyResult = {
    previewOnly: boolean;
    applicationRunId: string;
    appliedCount: number;
    partialCount: number;
    blockedCount: number;
    skippedCount: number;
    consequences: EventConsequence[];
    pendingConfirmations: string[];
    previewRows?: EventConsequencePreviewRow[];
    aggregateWarnings?: string[];
};
/** Portable stable fingerprint for browser + Node (no crypto import). */
export declare function stableConsequenceFingerprint(raw: string): string;
export declare function computeEventConsequenceId(input: {
    kind: EventConsequenceKind;
    payload: EventConsequencePayload;
    targets?: EventConsequenceTargets;
}): string;
export declare function parseEventConsequenceSet(raw: unknown): EventConsequenceSet | null;
export declare function readEventConsequencesFromMetadata(metadata: unknown): EventConsequence[];
export declare function mergeEventConsequenceSetIntoMetadata(metadata: Record<string, unknown>, consequences: EventConsequence[]): Record<string, unknown>;
export declare function dedupeEventConsequencesById(consequences: EventConsequence[]): EventConsequence[];
export declare function isEventConsequenceActionable(row: EventConsequence): boolean;
export declare function mapRouteChangeToEconomicSignal(payload: RouteChangePayload): {
    signal: 'trade_disruption';
    trafficWeight: number;
};
//# sourceMappingURL=eventConsequence.d.ts.map