/**
 * Phase 6 — world event consequences (GM-authored, manually applied).
 * Stored on event-lore wiki metadata (`event-{calendarEventId}`).
 */
export const EVENT_HAVEN_THREAT_SEVERITIES = ['low', 'rising', 'critical'] as const;
export type EventHavenThreatSeverity =
  (typeof EVENT_HAVEN_THREAT_SEVERITIES)[number];

export const EVENT_CONSEQUENCE_VERSION = 'event-consequence-v1';
export const EVENT_CONSEQUENCE_METADATA_KEY = 'eventConsequences';
export const EVENT_LORE_AUTO_GENERATED_METADATA_KEY = 'eventLoreAutoGenerated';

export const EVENT_CONSEQUENCE_KINDS = [
  'quest_hook',
  'alter_location',
  'route_change',
  'haven_threat',
] as const;

export type EventConsequenceKind = (typeof EVENT_CONSEQUENCE_KINDS)[number];

export const EVENT_CONSEQUENCE_APPLICATION_STATES = [
  'pending',
  'complete',
  'partial',
  'blocked',
] as const;

export type EventConsequenceApplicationState =
  (typeof EVENT_CONSEQUENCE_APPLICATION_STATES)[number];

export const EVENT_CONSEQUENCE_APPLICATION_SOURCES = [
  'manual_apply',
  'preview',
] as const;

export type EventConsequenceApplicationSource =
  (typeof EVENT_CONSEQUENCE_APPLICATION_SOURCES)[number];

export const QUEST_HOOK_MODES = ['discover_quest', 'open_thread'] as const;
export type QuestHookMode = (typeof QUEST_HOOK_MODES)[number];

export const ROUTE_CHANGE_SEVERITIES = ['minor', 'major'] as const;
export type RouteChangeSeverity = (typeof ROUTE_CHANGE_SEVERITIES)[number];

export const ROUTE_CHANGE_REASONS = ['war', 'banditry', 'disaster', 'other'] as const;
export type RouteChangeReason = (typeof ROUTE_CHANGE_REASONS)[number];

export type EventConsequenceTargets = {
  pageIds?: string[];
  havenIds?: string[];
  locationIds?: string[];
};

export type QuestHookPayload = {
  mode: QuestHookMode;
};

export type AlterLocationPayload = Record<string, never>;

export type RouteChangePayload = {
  severity?: RouteChangeSeverity;
  reason?: RouteChangeReason;
};

export type HavenThreatPayload = {
  label: string;
  severity?: EventHavenThreatSeverity | null;
  description?: string | null;
};

export type EventConsequencePayload =
  | QuestHookPayload
  | AlterLocationPayload
  | RouteChangePayload
  | HavenThreatPayload;

export type EventConsequenceApplication = {
  state: EventConsequenceApplicationState;
  appliedAtEpochMinute?: string;
  applicationRunId?: string;
  source?: EventConsequenceApplicationSource;
  warnings?: string[];
  pendingConfirmations?: string[];
};

export type EventConsequence = {
  id: string;
  kind: EventConsequenceKind;
  description?: string;
  targets?: EventConsequenceTargets;
  payload: EventConsequencePayload;
  application?: EventConsequenceApplication;
};

export type EventConsequenceSet = {
  version: typeof EVENT_CONSEQUENCE_VERSION;
  consequences: EventConsequence[];
};

export type EventConsequencePreviewRow = {
  consequenceId: string;
  kind: EventConsequenceKind;
  projectedState: 'complete' | 'partial' | 'blocked';
  summary: string;
  warnings: string[];
  pendingConfirmations: string[];
};

export type EventConsequenceApplyResult = {
  previewOnly: boolean;
  applicationRunId: string;
  appliedCount: number;
  partialCount: number;
  blockedCount: number;
  skippedCount: number;
  consequences: EventConsequence[];
  pendingConfirmations: string[];
  previewRows?: EventConsequencePreviewRow[];
  aggregateWarnings?: string[];
};

/** Portable stable fingerprint for browser + Node (no crypto import). */
export function stableConsequenceFingerprint(raw: string): string {
  let hash = 2166136261;
  for (let i = 0; i < raw.length; i += 1) {
    hash ^= raw.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return `ec-${(hash >>> 0).toString(16).padStart(8, '0')}`;
}

function sortedUnique(ids: string[] | undefined): string[] {
  if (!ids?.length) return [];
  return [...new Set(ids.map((id) => id.trim()).filter(Boolean))].sort();
}

function normalizePayloadForId(
  kind: EventConsequenceKind,
  payload: EventConsequencePayload,
): string {
  if (kind === 'quest_hook') {
    const p = payload as QuestHookPayload;
    return JSON.stringify({ mode: p.mode ?? 'discover_quest' });
  }
  if (kind === 'route_change') {
    const p = payload as RouteChangePayload;
    return JSON.stringify({
      severity: p.severity ?? 'minor',
      reason: p.reason ?? 'other',
    });
  }
  if (kind === 'haven_threat') {
    const p = payload as HavenThreatPayload;
    return JSON.stringify({
      label: (p.label ?? '').trim().toLowerCase(),
      severity: p.severity ?? null,
      description: (p.description ?? '').trim().toLowerCase(),
    });
  }
  return '{}';
}

export function computeEventConsequenceId(input: {
  kind: EventConsequenceKind;
  payload: EventConsequencePayload;
  targets?: EventConsequenceTargets;
}): string {
  const targetParts = [
    ...sortedUnique(input.targets?.pageIds),
    ...sortedUnique(input.targets?.havenIds),
    ...sortedUnique(input.targets?.locationIds),
  ].join(',');
  const raw = [
    input.kind,
    normalizePayloadForId(input.kind, input.payload),
    targetParts,
  ].join('|');
  return stableConsequenceFingerprint(raw);
}

function normalizeQuestHookMode(raw: unknown): QuestHookMode | null {
  if (typeof raw !== 'string') return null;
  const lower = raw.trim().toLowerCase();
  if ((QUEST_HOOK_MODES as readonly string[]).includes(lower)) {
    return lower as QuestHookMode;
  }
  return null;
}

function normalizeRouteSeverity(raw: unknown): RouteChangeSeverity | undefined {
  if (typeof raw !== 'string') return undefined;
  const lower = raw.trim().toLowerCase();
  if ((ROUTE_CHANGE_SEVERITIES as readonly string[]).includes(lower)) {
    return lower as RouteChangeSeverity;
  }
  return undefined;
}

function normalizeRouteReason(raw: unknown): RouteChangeReason | undefined {
  if (typeof raw !== 'string') return undefined;
  const lower = raw.trim().toLowerCase();
  if ((ROUTE_CHANGE_REASONS as readonly string[]).includes(lower)) {
    return lower as RouteChangeReason;
  }
  return undefined;
}

function parseTargets(raw: unknown): EventConsequenceTargets | undefined {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return undefined;
  const record = raw as Record<string, unknown>;
  const pageIds = Array.isArray(record.pageIds)
    ? record.pageIds.filter((v): v is string => typeof v === 'string')
    : undefined;
  const havenIds = Array.isArray(record.havenIds)
    ? record.havenIds.filter((v): v is string => typeof v === 'string')
    : undefined;
  const locationIds = Array.isArray(record.locationIds)
    ? record.locationIds.filter((v): v is string => typeof v === 'string')
    : undefined;
  if (!pageIds?.length && !havenIds?.length && !locationIds?.length) {
    return undefined;
  }
  return { pageIds, havenIds, locationIds };
}

function parsePayload(
  kind: EventConsequenceKind,
  raw: unknown,
): EventConsequencePayload {
  const record =
    raw && typeof raw === 'object' && !Array.isArray(raw)
      ? (raw as Record<string, unknown>)
      : {};
  switch (kind) {
    case 'quest_hook': {
      const mode = normalizeQuestHookMode(record.mode) ?? 'discover_quest';
      return { mode };
    }
    case 'route_change':
      return {
        severity: normalizeRouteSeverity(record.severity),
        reason: normalizeRouteReason(record.reason),
      };
    case 'haven_threat':
      return {
        label: typeof record.label === 'string' ? record.label.trim() : '',
        severity:
          typeof record.severity === 'string' &&
          (EVENT_HAVEN_THREAT_SEVERITIES as readonly string[]).includes(
            record.severity,
          )
            ? (record.severity as EventHavenThreatSeverity)
            : record.severity === null
              ? null
              : undefined,
        description:
          typeof record.description === 'string' ? record.description : null,
      };
    case 'alter_location':
    default:
      return {};
  }
}

function parseApplication(raw: unknown): EventConsequenceApplication | undefined {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return undefined;
  const record = raw as Record<string, unknown>;
  const stateRaw = record.state;
  if (
    typeof stateRaw !== 'string' ||
    !(EVENT_CONSEQUENCE_APPLICATION_STATES as readonly string[]).includes(stateRaw)
  ) {
    return undefined;
  }
  const warnings = Array.isArray(record.warnings)
    ? record.warnings.filter((v): v is string => typeof v === 'string')
    : undefined;
  const pendingConfirmations = Array.isArray(record.pendingConfirmations)
    ? record.pendingConfirmations.filter((v): v is string => typeof v === 'string')
    : undefined;
  const sourceRaw = record.source;
  const source =
    typeof sourceRaw === 'string' &&
    (EVENT_CONSEQUENCE_APPLICATION_SOURCES as readonly string[]).includes(sourceRaw)
      ? (sourceRaw as EventConsequenceApplicationSource)
      : undefined;
  return {
    state: stateRaw as EventConsequenceApplicationState,
    appliedAtEpochMinute:
      typeof record.appliedAtEpochMinute === 'string'
        ? record.appliedAtEpochMinute
        : undefined,
    applicationRunId:
      typeof record.applicationRunId === 'string' ? record.applicationRunId : undefined,
    source,
    warnings,
    pendingConfirmations,
  };
}

function parseConsequenceEntry(raw: unknown): EventConsequence | null {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return null;
  const record = raw as Record<string, unknown>;
  const kindRaw = record.kind;
  if (
    typeof kindRaw !== 'string' ||
    !(EVENT_CONSEQUENCE_KINDS as readonly string[]).includes(kindRaw)
  ) {
    return null;
  }
  const kind = kindRaw as EventConsequenceKind;
  const payload = parsePayload(kind, record.payload);
  const targets = parseTargets(record.targets);
  const id =
    typeof record.id === 'string' && record.id.trim()
      ? record.id.trim()
      : computeEventConsequenceId({ kind, payload, targets });
  const description =
    typeof record.description === 'string' ? record.description : undefined;
  const application = parseApplication(record.application);
  return {
    id,
    kind,
    description,
    targets,
    payload,
    application: application ?? { state: 'pending' },
  };
}

export function parseEventConsequenceSet(raw: unknown): EventConsequenceSet | null {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return null;
  const record = raw as Record<string, unknown>;
  if (record.version !== EVENT_CONSEQUENCE_VERSION) return null;
  if (!Array.isArray(record.consequences)) return null;
  const consequences: EventConsequence[] = [];
  const seenIds = new Set<string>();
  for (const entry of record.consequences) {
    const parsed = parseConsequenceEntry(entry);
    if (!parsed) continue;
    if (seenIds.has(parsed.id)) continue;
    seenIds.add(parsed.id);
    consequences.push(parsed);
  }
  return { version: EVENT_CONSEQUENCE_VERSION, consequences };
}

export function readEventConsequencesFromMetadata(metadata: unknown): EventConsequence[] {
  if (!metadata || typeof metadata !== 'object' || Array.isArray(metadata)) return [];
  const record = metadata as Record<string, unknown>;
  const set = parseEventConsequenceSet(record[EVENT_CONSEQUENCE_METADATA_KEY]);
  return set?.consequences ?? [];
}

export function mergeEventConsequenceSetIntoMetadata(
  metadata: Record<string, unknown>,
  consequences: EventConsequence[],
): Record<string, unknown> {
  return {
    ...metadata,
    [EVENT_CONSEQUENCE_METADATA_KEY]: {
      version: EVENT_CONSEQUENCE_VERSION,
      consequences,
    } satisfies EventConsequenceSet,
  };
}

export function dedupeEventConsequencesById(
  consequences: EventConsequence[],
): EventConsequence[] {
  const byId = new Map<string, EventConsequence>();
  for (const row of consequences) {
    const existing = byId.get(row.id);
    if (!existing) {
      byId.set(row.id, row);
      continue;
    }
    const existingState = existing.application?.state ?? 'pending';
    const nextState = row.application?.state ?? 'pending';
    if (existingState === 'complete' && nextState !== 'complete') {
      continue;
    }
    byId.set(row.id, row);
  }
  return [...byId.values()];
}

export function isEventConsequenceActionable(row: EventConsequence): boolean {
  const state = row.application?.state ?? 'pending';
  return state === 'pending' || state === 'partial' || state === 'blocked';
}

export function mapRouteChangeToEconomicSignal(payload: RouteChangePayload): {
  signal: 'trade_disruption';
  trafficWeight: number;
} {
  const severity = payload.severity ?? 'minor';
  return {
    signal: 'trade_disruption',
    trafficWeight: severity === 'major' ? 0.3 : 0.55,
  };
}
