"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ROUTE_CHANGE_REASONS = exports.ROUTE_CHANGE_SEVERITIES = exports.QUEST_HOOK_MODES = exports.EVENT_CONSEQUENCE_APPLICATION_SOURCES = exports.EVENT_CONSEQUENCE_APPLICATION_STATES = exports.EVENT_CONSEQUENCE_KINDS = exports.EVENT_LORE_AUTO_GENERATED_METADATA_KEY = exports.EVENT_CONSEQUENCE_METADATA_KEY = exports.EVENT_CONSEQUENCE_VERSION = exports.EVENT_HAVEN_THREAT_SEVERITIES = void 0;
exports.stableConsequenceFingerprint = stableConsequenceFingerprint;
exports.computeEventConsequenceId = computeEventConsequenceId;
exports.parseEventConsequenceSet = parseEventConsequenceSet;
exports.readEventConsequencesFromMetadata = readEventConsequencesFromMetadata;
exports.mergeEventConsequenceSetIntoMetadata = mergeEventConsequenceSetIntoMetadata;
exports.dedupeEventConsequencesById = dedupeEventConsequencesById;
exports.isEventConsequenceActionable = isEventConsequenceActionable;
exports.mapRouteChangeToEconomicSignal = mapRouteChangeToEconomicSignal;
/**
 * Phase 6 — world event consequences (GM-authored, manually applied).
 * Stored on event-lore wiki metadata (`event-{calendarEventId}`).
 */
exports.EVENT_HAVEN_THREAT_SEVERITIES = ['low', 'rising', 'critical'];
exports.EVENT_CONSEQUENCE_VERSION = 'event-consequence-v1';
exports.EVENT_CONSEQUENCE_METADATA_KEY = 'eventConsequences';
exports.EVENT_LORE_AUTO_GENERATED_METADATA_KEY = 'eventLoreAutoGenerated';
exports.EVENT_CONSEQUENCE_KINDS = [
    'quest_hook',
    'alter_location',
    'route_change',
    'haven_threat',
];
exports.EVENT_CONSEQUENCE_APPLICATION_STATES = [
    'pending',
    'complete',
    'partial',
    'blocked',
];
exports.EVENT_CONSEQUENCE_APPLICATION_SOURCES = [
    'manual_apply',
    'preview',
];
exports.QUEST_HOOK_MODES = ['discover_quest', 'open_thread'];
exports.ROUTE_CHANGE_SEVERITIES = ['minor', 'major'];
exports.ROUTE_CHANGE_REASONS = ['war', 'banditry', 'disaster', 'other'];
/** Portable stable fingerprint for browser + Node (no crypto import). */
function stableConsequenceFingerprint(raw) {
    let hash = 2166136261;
    for (let i = 0; i < raw.length; i += 1) {
        hash ^= raw.charCodeAt(i);
        hash = Math.imul(hash, 16777619);
    }
    return `ec-${(hash >>> 0).toString(16).padStart(8, '0')}`;
}
function sortedUnique(ids) {
    if (!ids?.length)
        return [];
    return [...new Set(ids.map((id) => id.trim()).filter(Boolean))].sort();
}
function normalizePayloadForId(kind, payload) {
    if (kind === 'quest_hook') {
        const p = payload;
        return JSON.stringify({ mode: p.mode ?? 'discover_quest' });
    }
    if (kind === 'route_change') {
        const p = payload;
        return JSON.stringify({
            severity: p.severity ?? 'minor',
            reason: p.reason ?? 'other',
        });
    }
    if (kind === 'haven_threat') {
        const p = payload;
        return JSON.stringify({
            label: (p.label ?? '').trim().toLowerCase(),
            severity: p.severity ?? null,
            description: (p.description ?? '').trim().toLowerCase(),
        });
    }
    return '{}';
}
function computeEventConsequenceId(input) {
    const targetParts = [
        ...sortedUnique(input.targets?.pageIds),
        ...sortedUnique(input.targets?.havenIds),
        ...sortedUnique(input.targets?.locationIds),
    ].join(',');
    const raw = [
        input.kind,
        normalizePayloadForId(input.kind, input.payload),
        targetParts,
    ].join('|');
    return stableConsequenceFingerprint(raw);
}
function normalizeQuestHookMode(raw) {
    if (typeof raw !== 'string')
        return null;
    const lower = raw.trim().toLowerCase();
    if (exports.QUEST_HOOK_MODES.includes(lower)) {
        return lower;
    }
    return null;
}
function normalizeRouteSeverity(raw) {
    if (typeof raw !== 'string')
        return undefined;
    const lower = raw.trim().toLowerCase();
    if (exports.ROUTE_CHANGE_SEVERITIES.includes(lower)) {
        return lower;
    }
    return undefined;
}
function normalizeRouteReason(raw) {
    if (typeof raw !== 'string')
        return undefined;
    const lower = raw.trim().toLowerCase();
    if (exports.ROUTE_CHANGE_REASONS.includes(lower)) {
        return lower;
    }
    return undefined;
}
function parseTargets(raw) {
    if (!raw || typeof raw !== 'object' || Array.isArray(raw))
        return undefined;
    const record = raw;
    const pageIds = Array.isArray(record.pageIds)
        ? record.pageIds.filter((v) => typeof v === 'string')
        : undefined;
    const havenIds = Array.isArray(record.havenIds)
        ? record.havenIds.filter((v) => typeof v === 'string')
        : undefined;
    const locationIds = Array.isArray(record.locationIds)
        ? record.locationIds.filter((v) => typeof v === 'string')
        : undefined;
    if (!pageIds?.length && !havenIds?.length && !locationIds?.length) {
        return undefined;
    }
    return { pageIds, havenIds, locationIds };
}
function parsePayload(kind, raw) {
    const record = raw && typeof raw === 'object' && !Array.isArray(raw)
        ? raw
        : {};
    switch (kind) {
        case 'quest_hook': {
            const mode = normalizeQuestHookMode(record.mode) ?? 'discover_quest';
            return { mode };
        }
        case 'route_change':
            return {
                severity: normalizeRouteSeverity(record.severity),
                reason: normalizeRouteReason(record.reason),
            };
        case 'haven_threat':
            return {
                label: typeof record.label === 'string' ? record.label.trim() : '',
                severity: typeof record.severity === 'string' &&
                    exports.EVENT_HAVEN_THREAT_SEVERITIES.includes(record.severity)
                    ? record.severity
                    : record.severity === null
                        ? null
                        : undefined,
                description: typeof record.description === 'string' ? record.description : null,
            };
        case 'alter_location':
        default:
            return {};
    }
}
function parseApplication(raw) {
    if (!raw || typeof raw !== 'object' || Array.isArray(raw))
        return undefined;
    const record = raw;
    const stateRaw = record.state;
    if (typeof stateRaw !== 'string' ||
        !exports.EVENT_CONSEQUENCE_APPLICATION_STATES.includes(stateRaw)) {
        return undefined;
    }
    const warnings = Array.isArray(record.warnings)
        ? record.warnings.filter((v) => typeof v === 'string')
        : undefined;
    const pendingConfirmations = Array.isArray(record.pendingConfirmations)
        ? record.pendingConfirmations.filter((v) => typeof v === 'string')
        : undefined;
    const sourceRaw = record.source;
    const source = typeof sourceRaw === 'string' &&
        exports.EVENT_CONSEQUENCE_APPLICATION_SOURCES.includes(sourceRaw)
        ? sourceRaw
        : undefined;
    return {
        state: stateRaw,
        appliedAtEpochMinute: typeof record.appliedAtEpochMinute === 'string'
            ? record.appliedAtEpochMinute
            : undefined,
        applicationRunId: typeof record.applicationRunId === 'string' ? record.applicationRunId : undefined,
        source,
        warnings,
        pendingConfirmations,
    };
}
function parseConsequenceEntry(raw) {
    if (!raw || typeof raw !== 'object' || Array.isArray(raw))
        return null;
    const record = raw;
    const kindRaw = record.kind;
    if (typeof kindRaw !== 'string' ||
        !exports.EVENT_CONSEQUENCE_KINDS.includes(kindRaw)) {
        return null;
    }
    const kind = kindRaw;
    const payload = parsePayload(kind, record.payload);
    const targets = parseTargets(record.targets);
    const id = typeof record.id === 'string' && record.id.trim()
        ? record.id.trim()
        : computeEventConsequenceId({ kind, payload, targets });
    const description = typeof record.description === 'string' ? record.description : undefined;
    const application = parseApplication(record.application);
    return {
        id,
        kind,
        description,
        targets,
        payload,
        application: application ?? { state: 'pending' },
    };
}
function parseEventConsequenceSet(raw) {
    if (!raw || typeof raw !== 'object' || Array.isArray(raw))
        return null;
    const record = raw;
    if (record.version !== exports.EVENT_CONSEQUENCE_VERSION)
        return null;
    if (!Array.isArray(record.consequences))
        return null;
    const consequences = [];
    const seenIds = new Set();
    for (const entry of record.consequences) {
        const parsed = parseConsequenceEntry(entry);
        if (!parsed)
            continue;
        if (seenIds.has(parsed.id))
            continue;
        seenIds.add(parsed.id);
        consequences.push(parsed);
    }
    return { version: exports.EVENT_CONSEQUENCE_VERSION, consequences };
}
function readEventConsequencesFromMetadata(metadata) {
    if (!metadata || typeof metadata !== 'object' || Array.isArray(metadata))
        return [];
    const record = metadata;
    const set = parseEventConsequenceSet(record[exports.EVENT_CONSEQUENCE_METADATA_KEY]);
    return set?.consequences ?? [];
}
function mergeEventConsequenceSetIntoMetadata(metadata, consequences) {
    return {
        ...metadata,
        [exports.EVENT_CONSEQUENCE_METADATA_KEY]: {
            version: exports.EVENT_CONSEQUENCE_VERSION,
            consequences,
        },
    };
}
function dedupeEventConsequencesById(consequences) {
    const byId = new Map();
    for (const row of consequences) {
        const existing = byId.get(row.id);
        if (!existing) {
            byId.set(row.id, row);
            continue;
        }
        const existingState = existing.application?.state ?? 'pending';
        const nextState = row.application?.state ?? 'pending';
        if (existingState === 'complete' && nextState !== 'complete') {
            continue;
        }
        byId.set(row.id, row);
    }
    return [...byId.values()];
}
function isEventConsequenceActionable(row) {
    const state = row.application?.state ?? 'pending';
    return state === 'pending' || state === 'partial' || state === 'blocked';
}
function mapRouteChangeToEconomicSignal(payload) {
    const severity = payload.severity ?? 'minor';
    return {
        signal: 'trade_disruption',
        trafficWeight: severity === 'major' ? 0.3 : 0.55,
    };
}
//# sourceMappingURL=eventConsequence.js.map