/** Notification types — mirrored in backend/src/lib/notifications/types.ts */
export const NotificationType = {
  JOIN_REQUEST_ACCEPTED: 'JOIN_REQUEST_ACCEPTED',
  JOIN_REQUEST_DENIED: 'JOIN_REQUEST_DENIED',
  JOIN_REQUEST_RECEIVED: 'JOIN_REQUEST_RECEIVED',
  ROLE_CHANGED: 'ROLE_CHANGED',
  OWNERSHIP_TRANSFER_OFFERED: 'OWNERSHIP_TRANSFER_OFFERED',
  OWNERSHIP_TRANSFER_COMPLETED: 'OWNERSHIP_TRANSFER_COMPLETED',
  OWNERSHIP_TRANSFER_DECLINED: 'OWNERSHIP_TRANSFER_DECLINED',
  OWNERSHIP_TRANSFER_EXPIRED: 'OWNERSHIP_TRANSFER_EXPIRED',
  MEMBER_DEPARTED: 'MEMBER_DEPARTED',
  SESSION_PUBLISHED: 'SESSION_PUBLISHED',
  SESSION_CHANGED: 'SESSION_CHANGED',
  SESSION_CANCELLED: 'SESSION_CANCELLED',
  SESSION_REMINDER_24H: 'SESSION_REMINDER_24H',
  RSVP_UPDATED: 'RSVP_UPDATED',
  EXPORT_READY: 'EXPORT_READY',
  EXPORT_FAILED: 'EXPORT_FAILED',
  IMPORT_COMPLETE: 'IMPORT_COMPLETE',
  IMPORT_FAILED: 'IMPORT_FAILED',
  GENERIC: 'GENERIC',
  MENTION_IN_PAGE: 'MENTION_IN_PAGE',
  CHARACTER_REFERENCED_IN_PAGE: 'CHARACTER_REFERENCED_IN_PAGE',
} as const;

export type NotificationTypeValue =
  (typeof NotificationType)[keyof typeof NotificationType];
