import {
  Anchor,
  Backpack,
  Bell,
  Bird,
  Bookmark,
  BookOpen,
  Bug,
  Building,
  Calendar,
  Castle,
  Church,
  Clock,
  Cloud,
  Compass,
  Crown,
  Droplet,
  Eye,
  EyeOff,
  FileText,
  Fish,
  Flag,
  Flame,
  Gem,
  GitBranch,
  Ghost,
  Gift,
  Hash,
  Heart,
  Home,
  Hourglass,
  Key,
  Landmark,
  Lock,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MessageCircle,
  Moon,
  Mountain,
  NotebookPen,
  Package,
  PawPrint,
  PenLine,
  ScrollText,
  Search,
  Shield,
  Ship,
  Skull,
  Sparkles,
  Star,
  Sun,
  Swords,
  Tag,
  Tags,
  Target,
  TrainFront,
  TreePine,
  Trophy,
  User,
  Users,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import catalog from './tagIconCatalog.json';

export const TAG_ICON_CATALOG_NAMES = catalog as string[];

export const TAG_ICON_CATALOG: Record<string, LucideIcon> = {
  tag: Tag,
  tags: Tags,
  hash: Hash,
  bookmark: Bookmark,
  star: Star,
  heart: Heart,
  flag: Flag,
  bell: Bell,
  'book-open': BookOpen,
  'scroll-text': ScrollText,
  'file-text': FileText,
  'notebook-pen': NotebookPen,
  'pen-line': PenLine,
  'map-pin': MapPin,
  map: Map,
  castle: Castle,
  mountain: Mountain,
  skull: Skull,
  swords: Swords,
  shield: Shield,
  user: User,
  users: Users,
  crown: Crown,
  gem: Gem,
  package: Package,
  backpack: Backpack,
  flame: Flame,
  droplet: Droplet,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  zap: Zap,
  sparkles: Sparkles,
  eye: Eye,
  'eye-off': EyeOff,
  lock: Lock,
  key: Key,
  search: Search,
  target: Target,
  compass: Compass,
  'tree-pine': TreePine,
  ghost: Ghost,
  bug: Bug,
  bird: Bird,
  fish: Fish,
  'paw-print': PawPrint,
  hourglass: Hourglass,
  calendar: Calendar,
  clock: Clock,
  megaphone: Megaphone,
  'message-circle': MessageCircle,
  mail: Mail,
  gift: Gift,
  trophy: Trophy,
  anchor: Anchor,
  ship: Ship,
  'train-front': TrainFront,
  home: Home,
  building: Building,
  church: Church,
  landmark: Landmark,
  'git-branch': GitBranch,
};

export function catalogLucideIcon(name: string): LucideIcon {
  return TAG_ICON_CATALOG[name] ?? Tag;
}
